#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Riku Kinjo
# SPDX-License-Identifier: BSD-3-Clause

import sys


read = sys.stdin.read().strip()
data = read.split()
end  = len(data)
maindata = float(data[0])
nchange  = float(data[0])

for i in range(1,end):
      if i % 2 == 0:
         if   data[i - 1] == '+':
           maindata += float(data[i])

         elif data[i - 1] == '-':
           maindata -= float(data[i])

         elif data[i - 1] == '*':
           maindata *= float(data[i])

         elif data[i - 1] == '/':
           maindata /= float(data[i])

if   maindata == nchange:
  print("変化なし")
else:
  if maindata > 256:
    print("error")
  elif maindata < 10:
       maindata = 0
       print(maindata)
  else:
       im = int(maindata)
       im = int(str(im).replace('4', '7').replace('6', '7'))
       print(im)
