#!/usr/bin/python3

import sys


read = sys.stdin.read().strip()
data = read.split()
end  = len(data)
maindata = float(data[0])
nchange  = float(data[0])

for i in range(1,end):
      if i % 2 == 0:
         if   data[i - 1] == '+':
           maindata += float(data[i])

         elif data[i - 1] == '-':
           maindata -= float(data[i])

         elif data[i - 1] == '*':
           maindata *= float(data[i])

         elif data[i - 1] == '/':
           maindata /= float(data[i])
#         else:
#           print("符号を入れてください")

if nchange  == maindata:
  print("変化なし")
else:
    fm = int(maindata)
    print(fm)
